default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: serverScVb1984

development:
  <<: *default
  database: euro_development

test:
  <<: *default
  database: euro_test

production:
  <<: *default
  database: euro_production
  username: root
